### ISSUE TITLE
메인페이지 스타일링

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/mju-festival-frontend#102]
## 💡Description
메인페이지 스타일링 수장

## ✅ Tasks
- [x] 동상 위치 변경
- [x] 동상 이미지 변경
- [x] 배경 색상 변경
