### ISSUE TITLE
분실물 페이지 수정 및 리팩토링

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/mju-festival-frontend#105]
## 💡Description
분실물 페이지 수정 및 리팩토링

## ✅ Tasks
- [x] 찾아간 분실물 모달 삭제 (찾음 처리 분실물도 일반 분실물처럼 조회는 가능)
- [x] 분실물 찾음 수령인 input 구현 
- [x] 함수 / 이미지 최적화
