### ISSUE TITLE
QR 관련 코드 수정 및 리팩토링

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/mju-festival-frontend#109]
## 💡Description
QR에 관련된 Bottom-sheet, QR-reader, 도장 코드 수정 및 리팩토링

## ✅ Tasks
- [x] Bottom-sheet text 추가
- [x] QR-reader 예외처리 리팩토링
- [x] QR 발급 예외처리 리팩토링
- [x] QR 재발급 타이머 & refresh 추가
- [x] 이미지 / 이외 코드 최적화

## 🚨 추가
- [x] 로그인 form checkbox (개인정보 동의) 이벤트 충돌 해결
