### ISSUE TITLE
부스 리스트 조회 방식 변경

### ISSUE THREAD

**Issue by hyunyeee** [mju-likelion/mju-festival-frontend#116]
## 💡Description
API 문서 변경에 따라 부스 리스트 띄우는 방식 변경

## ✅ Tasks
- [x] 페이징(무한스크롤) 삭제
- [x] 중복 선택 가능하도록 변경
- [x] 부스 리스트 필드 변경
