### ISSUE TITLE
공지사항 페이지 관련 이슈 및 리팩터링

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/mju-festival-frontend#117]
## 💡Description
공지사항 페이지 외 이슈들 수정

## ✅ Tasks
- [x] 공지사항 페이징 1/0
- [x] 최신순, 나중순 이슈
- [x] 메인페이지 텍스트 외의 버튼 커서 포인터 설정
- [x] 공지사항 뒤로가기시 메인화면
- [x] 드롭다운 활성시 외부 클릭 확인
- [x] 로딩중 표시 및 컴포넌트 분리
- [x] 불필요한 상태 관리 제거
- [x] 헤더 변경
