### ISSUE TITLE
디테일한 스타일 수정

### ISSUE THREAD

**Issue by hyunyeee** [mju-likelion/mju-festival-frontend#127]
## 💡Description
페이지 관계 없이 전체적으로 디테일한 스타일을 수정합니다

## ✅ Tasks
- [x] 로그인 input 배경색 제거
- [x] 부스 리스트 조회 카테고리 선택 버튼 사이즈
- [x] 부스 리스트 부서명 추가
- [x] 부스 디테일 페이지 이미지 사이즈 및 스타일 수정
- [x] 부스 정보 수정 페이지 스타일 수정
