### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/mju-festival-frontend#13]
## 💡Description
메인 페이지의 와이어프레임 구현

## ✅ Tasks
- [x] 날짜
- [x] 링크 바로가기 메뉴
  - [x] ios, android에 따른 설치 링크 연결
- [x] 축제 정보 메뉴
