### ISSUE TITLE
각 페이지 오류 수정 및 UI 변경사항 반영

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/mju-festival-frontend#139]
## 💡Description
페이지 별로 오류 수정 및 UI 변경사항을 반영한다.

## ✅ Tasks
- [x] QR 새로고침 재발급 이후 타이머 재작동
- [x] QR 발급 시점 페이지 렌더링 -> 바텀 시트 열릴 때로 변경
- [x] Not Found 페이지 text 및 UI 수정
- [x] QR 촬영 카메라 예외 처리 수정
- [x] 페이지 bottom 여백 설정 (footer)
- [x] 공지사항/분실물 페이지 내 DropDown 수정
- [x] 도장판 UI 변경사항 반영 (부스 이름 표시)
