### ISSUE TITLE
부스 스타일 수정

### ISSUE THREAD

**Issue by hyunyeee** [mju-likelion/mju-festival-frontend#161]
## 💡Description
이미지 스타일 수정 및 이벤트 참여 부스 표시

## ✅ Tasks
- [x] 이미지 스타일 수정
- [x] 이벤트 참여 부스 표시
- [x] 이벤트 참여 부스만 QR 발급이 가능하도록 수정
- [x] 로그인 상태에서는 설정 페이지에서 로그인 페이지 버튼이 뜨지 않도록 수정
