### ISSUE TITLE
스타일 수정

### ISSUE THREAD

**Issue by hyunyeee** [mju-likelion/mju-festival-frontend#181]
## 💡Description
스타일 수정

## ✅ Tasks
- [x] 로그인 폼 간격 수정
- [x] 이벤트 부스 스타일 수정
- [x] 검색 CSS 수정
- [x] 플로팅 버튼 화면 넘치는 현상 수정
- [x] 관리자용 로그인 버튼 마진 수정
