### ISSUE TITLE
스타일링 수정 hotfix

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/mju-festival-frontend#196]
## 💡Description
스타일링 수정

## ✅ Tasks
- [x] 이벤트 참여 부스 스타일 수정
- [x] 랜딩페이지 이미지 수정
- [x] 플로팅 버튼 스타일 수정
- [x] 수령인 정보 입력 UI 깨짐 수정
