### ISSUE TITLE
부스 방문 API 연결 함수/전체 스타일링 수정 hotfix

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/mju-festival-frontend#201]
## 💡Description
부스 방문 API 연결 함수/전체 스타일링 수정 hotfix

## ✅ Tasks
- [x] 부스 방문 API 연결 함수 asnyc/await 추가 (QR 중복 인식 방지)
- [x] Setting 페이지 로그아웃 confirm시 navigate 위치 변경
- [x] 이벤트 참여 부스 이름 추가 / min-width 170px로 변경
- [x] 부스 상세 조회 페이지 description white-space : pre-wrap으로 변경
