### ISSUE TITLE
부스 게시글 수정 기능 구현

### ISSUE THREAD

**Issue by hyunyeee** [mju-likelion/mju-festival-frontend#23]
## 💡Description
부스 관리자는 부스 소개 글 수정이 가능하다.

## ✅ Tasks
- [x] 부스 단건조회 페이지 역할에 따른 뷰 구현
- [ ] 부스 관리자 확인 API 연결
- [x] 부스 게시글 수정 기능 - 부스 관리자
- [x] 수정 API 연결
