### ISSUE TITLE
공지사항 세부 조회 페이지 스타일링

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/mju-festival-frontend#55]
## 💡Description
공지사항 세부 조회 페이지 css 적용

## ✅ Tasks
- [x] 이미지 영역
- [x] 본문 영역
- [x] 인스타 링크 버튼
- [x] 수정하기, 삭제하기 버튼
- [x] 삭제 모달
- [x] role에 따른 버튼 노출
