### ISSUE TITLE
분실물 상세 조회 페이지 스타일링

### ISSUE THREAD

**Issue by constantly-dev** [mju-likelion/mju-festival-frontend#59]
## 💡Description
분실물 상세 조회 페이지 스타일 적용

## ✅ Tasks
- [x] 관리자, 일반 유저 역할에 따른 버튼/텍스트 UI
- [x] 삭제 유의사항 모달
- [x] 제목/사진/내용
