### ISSUE TITLE
공지사항 세부 조회 페이지

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/mju-festival-frontend#6]
## 💡Description
업로드된 세부 공지사항을 조회하는 페이지 구현

## ✅ Tasks
- [x] 세부 페이지 Header 구현
- [x] 이미지 조회
- [x] 본문 및 텍스트 조회
- [x] 등록날짜
- [x] 전체 공지사항에서 클릭시 상세 공지사항으로 이동
