### ISSUE TITLE
공지사항 전체 조회 스타일링

### ISSUE THREAD

**Issue by zelkovaria** [mju-likelion/mju-festival-frontend#67]
## 💡Description
공지사항 전체 조회 페이지 스타일링 적용

## ✅ Tasks
- [x] info Text
- [ ] 정렬 버튼
- [x] 제목, 본문 일정 길이 이상 처리
- [x] notice component + 배경색
- [ ] 이전, 다음 버튼
- [x] 게시물 작성 버튼
